
//----------------------------------------------------
// The following code was generated by C# CUP v0.1
// 10/29/2010 2:50:43 PM
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class Sym {
  /* terminals */
  public const int EOF = 0;
  public const int RBRACKET = 12;
  public const int LBRACKET = 17;
  public const int RPAREN = 19;
  public const int FIX = 14;
  public const int IMPLIES = 5;
  public const int PRINCIPAL = 24;
  public const int SAID = 8;
  public const int KNOWS = 7;
  public const int EQUAL = 13;
  public const int TRUE = 6;
  public const int COMMA = 2;
  public const int NUMBER = 26;
  public const int PROVISO = 10;
  public const int FROM = 22;
  public const int error = 1;
  public const int TO = 21;
  public const int IMPLIED = 9;
  public const int TOKEN = 15;
  public const int CONDITIONAL = 11;
  public const int QUESTION = 23;
  public const int FUNCTION = 25;
  public const int LPAREN = 18;
  public const int PLUS = 4;
  public const int COLON = 20;
  public const int SEMI = 3;
  public const int VARIABLE = 16;
	}
